name: release-v1-CI/CD

# When push/pr, this action will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  CI_CD:
    runs-on: ubuntu-latest
    steps:          
      - uses: actions/checkout@v2
      
      # install java 8
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '8'
          
      # CI
      - name: Begin CI
        run: echo Begin CI!
      - name: Maven Package
        run: |
          mvn clean
          mvn package -Dmaven.test.skip=true
      - name: End CI
        run: echo End CI!
 
      # CD
      - name: Begin CD
        run:  echo Begin CD!
      - name: Deploy File
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: "root"
          password: ${{ secrets.ALIYUN_PWD }}
          source: "./target/root.war"
          target: "/opt/jetty/webapps"
      - name: ssh
        run: |
          eval $(ssh-agent -s)
          echo "${{secrets.SSH_PRIVATE_KEY}}" > deploy.key
          mkdir -p ~/.ssh
          chmod 0600 deploy.key
          ssh-add deploy.key
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh root@${{secrets.SERVER_IP}} "mv -f /opt/jetty/webapps/target/root.war /opt/jetty/webapps/"
      - name: End CD
        run: echo End CD!
